### ISSUE TITLE
Square root scale and Log scale in emhist.m

### ISSUE THREAD

**Issue by Jasim9** [ogdenkev/expmixdist#1]
Could you please explain the use of log scale and square root scale in the PDF plot? I am unable to find a reference for why square root scale works for log?

**Comment by ogdenkev** [comment]
Good question. In the field of ion channel kinetics and mechanisms, it has
been the common practice to display exponential mixture distributions as
the square root of the frequency versus the logarithm of the data for over
20 years. I think the paper that started this practice was "Data
transformations for improved display and fitting of single channel dwell
time histograms" by Sigworth and Sine in Biophysical Journal 1987,
https://www.ncbi.nlm.nih.gov/pubmed/2447968

**Comment by Jasim9** [comment]
Thank you for the paper link, looks like an interesting read. 
I haven't actually seen the log and square root scales in any literature I have come across, and it was surprising that I wasn't able to find any articles myself as well.
